name: Docker Build
on: push
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
steps:
- name: Check out code
  uses: actions/checkout@v3
- name: Build docker images
  run: docker build -t script2docker/myplot . < Dockerfile
- name: Run
  run: docker run -it --rm -v $PWD/data:/data -v $PWD/output:/output script2docker/myplot
